// Copyright © 2024-25 The Johns Hopkins Applied Physics Laboratory LLC.
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU Affero General Public License,
// version 3, as published by the Free Software Foundation.  If you
// would like to purchase a commercial license for this software, please
// contact APL’s Tech Transfer at 240-592-0817 or
// techtransfer@jhuapl.edu.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public
// License along with this program.  If not, see
// <https://www.gnu.org/licenses/>.

use std::collections::HashMap;
use std::convert::TryFrom;
use std::fmt::Display;
use std::hash::Hash;
use std::marker::PhantomData;
use std::time::Instant;

use constellation_auth::authn::SessionAuthN;
use constellation_common::net::DatagramXfrm;
use constellation_common::net::DatagramXfrmCreate;
use constellation_common::net::NegotiatorStart;
use constellation_common::net::Receiver;
use constellation_common::net::Sender;
use constellation_common::net::Socket;
use constellation_common::retry::Retry;
use constellation_common::retry::RetryResult;
use mio::event::Source;

use crate::channels::SessionNegoState;
use crate::far::AcquiredResolver;
use crate::far::FarChannelAcquiredResolve;
use crate::far::FarChannelCreate;
use crate::far::FarChannelFlows;
use crate::far::flows::BufferedFlow;
use crate::far::flows::Flow;
use crate::far::flows::Flows;

/// Retry information for a given possible [Flows] instance.
struct FlowsRetry {
    nfailures: usize,
    retry_when: Instant
}

enum FlowNegoState<F, InboundPending, OutboundPending, AuthN> {
    /// Outbound session negotiation is pending.
    Outbound {
        /// The pending negotiation state.
        pending: SessionNegoState<F, OutboundPending, AuthN>
    },
    /// Outbound session negotiation is pending.
    Inbound {
        /// The pending negotiation state.
        pending: SessionNegoState<F, InboundPending, AuthN>
    },
    /// A session has already been established.
    Active {
    }
}

struct FlowsEntry<F, Sock, InboundNego, OutboundNego, AuthN, Xfrm>
where
    F: Flow,
    Sock: Receiver + Sender + Source,
    Sock::Addr: From<Xfrm::LocalAddr>,
    InboundNego: NegotiatorStart<F, BufferedFlow<Sock, Xfrm>>,
    OutboundNego: NegotiatorStart<F, BufferedFlow<Sock, Xfrm>>,
    Xfrm: DatagramXfrm,
    Xfrm::LocalAddr: From<Sock::Addr>
{
    state: Option<FlowNegoState<F, InboundNego::Pending,
                                OutboundNego::Pending, AuthN>>,
    flow: Flows<F, Sock, InboundNego, OutboundNego, Xfrm>,
    retry: FlowsRetry
}

struct AcquiredEntry<Channel, AuthN, Xfrm, InnerXfrm>
where
    Channel: FarChannelFlows<Xfrm, InnerXfrm> + FarChannelCreate,
    <Channel::Socket as Socket>::Addr: TryFrom<Xfrm::LocalAddr>,
    <<Channel::Socket as Socket>::Addr as TryFrom<Xfrm::LocalAddr>>::Error:
        Display,
    AuthN: Clone + SessionAuthN<Channel::Flow>,
    Xfrm: DatagramXfrmCreate<Addr = Channel::Param>,
    Xfrm::CreateParam: Clone + Default,
    Xfrm::LocalAddr: From<<Channel::Socket as Socket>::Addr>,
    InnerXfrm: DatagramXfrm,
    Channel::Acquired: FarChannelAcquiredResolve<Resolved = Channel::Param>,
    Channel::Param: Clone + Display + Eq + Hash + PartialEq {
    authn: PhantomData<AuthN>,
    xfrm: PhantomData<Xfrm>,
    /// Acquired value from the channel.
    acquired: Channel::Acquired,
    /// Resolver generated by the acquired value.
    resolver: AcquiredResolver<Channel::Param>,
    /// Current set of [Flows] for the various
    /// [Param](FarChannelSocket::Param)s.
    ///
    /// An acquired far channel allows sockets to be created, but
    /// there may be multiple possible configurations that can be set
    /// up.
    flows: HashMap<
        Channel::Param,
        FlowsEntry<Channel::Flow, Channel::Socket, Channel::InboundNego,
                   Channel::OutboundNego, AuthN, Xfrm>
    >
}

struct ChannelEntry<Channel, AuthN, Xfrm, InnerXfrm>
where
    Channel: FarChannelFlows<Xfrm, InnerXfrm> + FarChannelCreate,
    <Channel::Socket as Socket>::Addr: TryFrom<Xfrm::LocalAddr>,
    <<Channel::Socket as Socket>::Addr as TryFrom<Xfrm::LocalAddr>>::Error:
        Display,
    AuthN: Clone + SessionAuthN<Channel::Flow>,
    Xfrm: DatagramXfrmCreate<Addr = Channel::Param>,
    Xfrm::CreateParam: Clone + Default,
    Xfrm::LocalAddr: From<<Channel::Socket as Socket>::Addr>,
    InnerXfrm: DatagramXfrm,
    Channel::Acquired: FarChannelAcquiredResolve<Resolved = Channel::Param>,
    Channel::Param: Clone + Display + Eq + Hash + PartialEq {
    /// Base [FarChannel](crate::far::FarChannel) object.
    channel: Channel,
    /// Acquired value and flows, if a value has been acquired.
    ///
    /// This is used to store when to retry, if
    /// [Retry](RetryResult::Retry) is present.
    acquired: RetryResult<AcquiredEntry<Channel, AuthN, Xfrm, InnerXfrm>>,
    /// Retry configuration.
    retry: Retry
}
